# AWS Secrets Manager secret to store server passwords
resource "aws_secretsmanager_secret" "palworld_passwords" {
  name_prefix             = "${var.project_name}-passwords-"
  description             = "Palworld server passwords (auto-generated by Terraform)"
  recovery_window_in_days = 7 # Allow 7 days to recover if accidentally deleted

  tags = {
    Name        = "${var.project_name}-passwords"
    Application = "Palworld"
  }
}

# Store passwords as JSON in the secret
resource "aws_secretsmanager_secret_version" "palworld_passwords" {
  secret_id = aws_secretsmanager_secret.palworld_passwords.id

  secret_string = jsonencode({
    server_password = random_password.server_password.result
    admin_password  = random_password.admin_password.result
    server_ip       = aws_eip.palworld.public_ip
    server_port     = 8211
    dashboard_url   = "http://${aws_eip.palworld.public_ip}"
    created_at      = timestamp()
    notes           = "Server password: give to players. Admin password: keep secret for RCON/dashboard."
  })

  lifecycle {
    ignore_changes = [
      # Ignore timestamp changes on subsequent applies
      secret_string
    ]
  }
}

# AWS Secrets Manager secret for SSH private key backup
resource "aws_secretsmanager_secret" "ssh_private_key" {
  name_prefix             = "${var.project_name}-ssh-key-"
  description             = "SSH private key for server access (ED25519)"
  recovery_window_in_days = 7 # Allow 7 days to recover if accidentally deleted

  tags = {
    Name        = "${var.project_name}-ssh-private-key"
    Application = "Palworld"
  }
}

# Store SSH private key in Secrets Manager
resource "aws_secretsmanager_secret_version" "ssh_private_key" {
  secret_id = aws_secretsmanager_secret.ssh_private_key.id

  secret_string = jsonencode({
    private_key     = tls_private_key.palworld_ssh.private_key_openssh
    public_key      = tls_private_key.palworld_ssh.public_key_openssh
    key_algorithm   = tls_private_key.palworld_ssh.algorithm
    server_ip       = aws_eip.palworld.public_ip
    ssh_command     = "ssh -i palworld-server-key.pem ubuntu@${aws_eip.palworld.public_ip}"
    created_at      = timestamp()
    notes           = "ED25519 SSH private key for server access. Keep secure! Also saved locally as palworld-server-key.pem"
  })

  lifecycle {
    ignore_changes = [
      # Ignore timestamp changes on subsequent applies
      secret_string
    ]
  }
}

# IAM policy to allow EC2 to read secrets (if needed for future features)
resource "aws_iam_role_policy" "palworld_secrets_read" {
  name = "secrets-manager-read"
  role = aws_iam_role.palworld_ec2.id

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Effect = "Allow"
        Action = [
          "secretsmanager:GetSecretValue",
          "secretsmanager:DescribeSecret"
        ]
        Resource = [
          aws_secretsmanager_secret.palworld_passwords.arn,
          aws_secretsmanager_secret.ssh_private_key.arn
        ]
      }
    ]
  })
}
